![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [76]:
# Import necessary packages
import pandas as pd
import numpy as np

airbnb_price = pd.read_csv("data/airbnb_price.csv")
airbnb_room_type = pd.read_excel("data/airbnb_room_type.xlsx")
airbnb_last_review = pd.read_csv("data/airbnb_last_review.tsv", sep="\t")

In [77]:
airbnb_price.head()

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown

In [78]:
airbnb_room_type.head()

   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt

In [79]:
airbnb_last_review.head()

   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [80]:
df = airbnb_price.merge(airbnb_room_type, on="listing_id").merge(airbnb_last_review, on="listing_id")
df.head()

   listing_id        price  ...    host_name   last_review
0        2595  225 dollars  ...     Jennifer   May 21 2019
1        3831   89 dollars  ...  LisaRoxanne  July 05 2019
2        5099  200 dollars  ...        Chris  June 22 2019
3        5178   79 dollars  ...     Shunichi  June 24 2019
4        5238  150 dollars  ...          Ben  June 09 2019

[5 rows x 7 columns]

In [81]:
df["last_review"] = pd.to_datetime(df["last_review"])
print(df.dtypes)
df.head()

listing_id              int64
price                  object
nbhood_full            object
description            object
room_type              object
host_name              object
last_review    datetime64[ns]
dtype: object

   listing_id        price  ...    host_name last_review
0        2595  225 dollars  ...     Jennifer  2019-05-21
1        3831   89 dollars  ...  LisaRoxanne  2019-07-05
2        5099  200 dollars  ...        Chris  2019-06-22
3        5178   79 dollars  ...     Shunichi  2019-06-24
4        5238  150 dollars  ...          Ben  2019-06-09

[5 rows x 7 columns]

### What are the dates of the earliest and most recent reviews?

In [82]:
first_reviewed = df["last_review"].min()
last_reviewed = df["last_review"].max()
print(first_reviewed, last_reviewed)

2019-01-01 00:00:00 2019-07-09 00:00:00

### How many of the listings are private rooms?

In [83]:
df["room_type"] = df["room_type"].str.lower()
nb_private_rooms = len(
    df[df["room_type"] == "private room"]
)
nb_private_rooms

11356

### What is the average listing price?

In [84]:
df["price"] = (df["price"].str.strip("dollars")).str.strip().astype(float)
avg_price = df["price"].mean().round(2)
avg_price

141.78

In [85]:
review_dates = pd.DataFrame(
    {
        "first_reviewed": [first_reviewed],
        "last_reviewed": [last_reviewed],
        "nb_private_rooms": [nb_private_rooms],
        "avg_price": [avg_price]
    }
)